# Generated by Django 4.2.3 on 2023-07-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
